---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: auth-app
spec:
  replicas: 1
  strategy:
   type: RollingUpdate
   rollingUpdate:
    maxUnavailable: 50%
    maxSurge: 50%
  template:
    metadata:
      labels:
        app: invoice-auth
        tier: backend
        track: stable
    spec:
      containers:
      - name: auth-app
        image: BUILD_TAG
        resources:
         requests:
          cpu: 100m
          memory: 100Mi
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
