---
apiVersion: v1
kind: Service
metadata:
  name: auth-app
  labels:
    app: invoice-auth
    tier: backend
    track: stable
spec:
  type: NodePort
  selector:
    app: invoice-auth
    tier: backend
    track: stable
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
